# Generated by Django 6.1.1 on 2026-09-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='boilers/', verbose_name='Rasm')),
                ('power', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quvvati (kVt)')),
                ('heating_area', models.CharField(blank=True, max_length=50, null=True, verbose_name='Isitish maydoni (kv.m)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Narxi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='doors/', verbose_name='Rasm')),
                ('width', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kengligi (sm)')),
                ('height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Balandligi (sm)')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Materiali')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Narxi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='pots/', verbose_name='Rasm')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hajmi (litr)')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Materiali')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Narxi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
            ],
        ),
    ]
