# Generated by Django 6.1.1 on 2026-09-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_boiler_description_ru_boiler_description_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boiler',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='boiler',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='doors',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='doors',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='boiler',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube video havolasi (linki)'),
        ),
    ]
