# Generated by Django 6.1.1 on 2026-09-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_boiler_description_ru_remove_boiler_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner sarlavhasi')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Banner rasmi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
