# Generated by Django 6.1.1 on 2026-09-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doors',
        ),
        migrations.DeleteModel(
            name='Pot',
        ),
        migrations.AddField(
            model_name='boiler',
            name='fuel_type',
            field=models.CharField(choices=[('coal', "Ko'mirda ishlaydigan"), ('gas', 'Gazda ishlaydigan')], default='coal', max_length=10, verbose_name="Yoqilg'i turi"),
        ),
    ]
