# Generated by Django 6.1.1 on 2026-09-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_doors_delete_pot_boiler_fuel_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
