# Generated by Django 6.1.1 on 2026-09-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='fuel_type',
            field=models.CharField(choices=[('coal', "Ko'mir"), ('gas', 'Gaz')], default='coal', max_length=10, verbose_name="Yoqilg'i turi"),
        ),
    ]
