# Generated by Django 6.1.1 on 2026-10-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_boiler_fuel_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boiler',
            options={'verbose_name': 'Qozon', 'verbose_name_plural': 'Qozonlar'},
        ),
        migrations.CreateModel(
            name='BoilerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='boilers/extra/', verbose_name='Rasm')),
                ('boiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.boiler')),
            ],
            options={
                'verbose_name': "Qo'shimcha rasm",
                'verbose_name_plural': "Qo'shimcha rasmlar",
                'ordering': ['id'],
            },
        ),
    ]
