# Generated by Django 6.1.1 on 2026-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_boiler_options_boilerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='boiler',
            name='automation',
            field=models.TextField(blank=True, null=True, verbose_name='Avtomatika / Aqilli boshqaruv'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='automation_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Avtomatika / Aqilli boshqaruv'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='automation_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Avtomatika / Aqilli boshqaruv'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='bunker_volume',
            field=models.CharField(blank=True, help_text='Faqat son (masalan: 100)', max_length=50, null=True, verbose_name='Bunker hajmi'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='chamber_volume',
            field=models.CharField(blank=True, help_text='Faqat son (masalan: 120)', max_length=50, null=True, verbose_name='Yonish kamerasi hajmi'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='control_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Boshqaruv tizimi'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='control_system_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Boshqaruv tizimi'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='control_system_uz_cyrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Boshqaruv tizimi'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Masalan: 640 x 500 x 720', max_length=100, null=True, verbose_name="O'lchami (U × E × B)"),
        ),
        migrations.AddField(
            model_name='boiler',
            name='equipment_set',
            field=models.TextField(blank=True, null=True, verbose_name='Komplektatsiya'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='equipment_set_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Komplektatsiya'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='equipment_set_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Komplektatsiya'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='fuel_consumption',
            field=models.CharField(blank=True, help_text='Faqat son (masalan: 6)', max_length=50, null=True, verbose_name="Yoqilg'i sarfi"),
        ),
        migrations.AddField(
            model_name='boiler',
            name='power_supply',
            field=models.CharField(blank=True, help_text='Faqat son (masalan: 220)', max_length=50, null=True, verbose_name="Elektr ta'minoti"),
        ),
        migrations.AddField(
            model_name='boiler',
            name='safety_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xavfsizlik tizimi'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='safety_system_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xavfsizlik tizimi'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='safety_system_uz_cyrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xavfsizlik tizimi'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='weight',
            field=models.CharField(blank=True, help_text='Faqat son (masalan: 700)', max_length=50, null=True, verbose_name="Og'irligi"),
        ),
        migrations.AddField(
            model_name='boiler',
            name='working_pressure',
            field=models.CharField(blank=True, help_text='Faqat son kiriting (masalan: 2)', max_length=50, null=True, verbose_name='Ish bosimi'),
        ),
        migrations.AddField(
            model_name='boiler',
            name='working_time',
            field=models.CharField(blank=True, help_text='Faqat son (masalan: 12)', max_length=50, null=True, verbose_name='Bir marta yuklashda ishlash vaqti'),
        ),
    ]
